config/routes.rb
Rails.application.routes.draw do

  devise_for :customers, path: 'customer', controllers: {
    sessions: "customers/sessions",
    registrations: "customers/registrations",
    passwords: "customers/passwords"
  }
  devise_for :admins, path: 'admin', controllers: {
    sessions: "admins/sessions"
  }

  namespace :admin do
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    patch 'orders/:order_id/order_details/:id' => 'order_details#update', as: 'order_detail'
  end
  get 'admin' => 'admin/homes#top'

  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'

    get 'customers/mypage' => 'customers#show'
    get 'customers/edit' => 'customers#edit'
    patch 'customers' => 'customers#update'
    put 'customers' => 'customers#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw'

    resources :addresses, only: [:index, :edit, :create, :update, :destroy]

    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]


    resources :items, only: [:index, :show]

    get 'orders/thanks' => 'orders#thanks'
    resources :orders, only: [:new, :create, :index, :show]
    post 'orders/confirm' => 'orders#confirm'

  end


end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy

  def active_for_authentication?
    super && (self.is_deleted == false)
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    @customers = Customer.all.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path
  end

  private
  def customer_params
  		params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :address, :postal_code, :telephone_number, :email, :is_deleted)
  end

end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  def after_sign_up_path_for(resource)
 	  customers_mypage_path
  end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController

  before_action :reject_customer, only: [:create]

  protected

  def reject_customer
    @customer = Customer.find_by(email: params[:customer][:email].downcase)
    if @customer
      if (@customer.valid_password?(params[:customer][:password]) && (@customer.active_for_authentication? == false))
        flash[:error] = "退会済みです。"
        redirect_to new_customer_session_path
      end
    else
      flash[:error] = "必須項目を入力してください。"
    end
  end
end
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-5 offset-sm-1 my-4">
			<h4 class="text-center bg-light"><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</h4>
		</div>
	</div>
	<div class="row">
	  <div class="col-sm-8 offset-sm-1 mt-4">

	    <%= form_with model: [:admin, @customer], local:true do |f| %>
	    <div class="form-group row">
	    	<label for="inputId" class="col-sm-3 small col-form-label">会員ID</label>
	    	<div class="col-sm-4"><%= @customer.id %></div>
	    </div>
	    <div class="form-group row">
	    	<label for="inputName" class="col-sm-3 small col-form-label">名前</label>
	      <div class="col-sm-4">
	      	<%= f.text_field :last_name, class: "form-control" %>
	      </div>
	      <div class="col-sm-4">
	      	 <%= f.text_field :first_name, class: "form-control" %>
	      </div>
	    </div>
	    <div class="form-group row">
	    	<label for="inputNameKana" class="col-sm-3 col-form-label small">フリガナ</label>
	      <div class="col-sm-4">
	      	<%= f.text_field :last_name_kana, class: "form-control" %>
	      </div>
	      <div class="col-sm-4">
	      	<%= f.text_field :first_name_kana, class: "form-control" %>
	      </div>
	    </div>
	    <div class="form-group row">
	    	<label for="inputPostalCode" class="col-sm-3 col-form-label small">郵便番号</label>
	    	<div class="col-sm-4">
	    		<%= f.text_field :postal_code, class: "form-control" %>
	    	</div>
	    </div>
	    <div class="form-group row">
	    	<label for="inputAddress" class="col-sm-3 col-form-label small">住所</label>
	    	<div class="col-sm-9">
	    		<%= f.text_field :address, class: "form-control w-75" %>
	    	</div>
	    </div>
	    <div class="form-group row">
	    	<label for="inputTelephoneNumber" class="col-sm-3 col-form-label small">電話番号</label>
	    	<div class="col-sm-4">
	    		<%= f.text_field :telephone_number, class: "form-control" %>
	    	</div>
	    </div>
	    <div class="form-group row">
	    	<label for="inputEmail" class="col-sm-3 col-form-label small">メールアドレス</label>
	    	<div class="col-sm-4">
	    		<%= f.email_field :email, class: "form-control" %>
	    	</div>
	    </div>
	    <div class="form-group row">
        <label for="inputstatus" class="col-sm-3 col-form-label">会員ステータス</label>
        <div class="col-sm-6">
          <div class="form-check form-check-inline">
            <%= f.radio_button :is_deleted, :false, class: "form-check-input" %>
            <label class="form-check-label" for="inlineCheckboxTrue">有効</label>
          </div>
          <div class="form-check form-check-inline">
            <%= f.radio_button :is_deleted, :true, class: "form-check-input" %>
            <label class="form-check-label" for="inlineCheckboxFalse">退会</label>
          </div>
        </div>
      </div>
    </div>
    <div class="col-sm-2 offset-sm-3 mt-4">
      <%= f.submit '変更を保存', class: "btn btn-success btn-lg" %>
    </div>
    <% end %>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-3 offset-sm-1 my-4">
			<h4 class="text-center bg-light">会員一覧</h4>
		</div>
    <table class="table col-sm-10 offset-sm-1">
      <thead class="thead-light">
        <tr>
          <th>会員ID</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @customers.each do |customer| %>
        <tr>
          <td><%= customer.id %></td>
          <td>
            <%= link_to admin_customer_path(customer.id) do %>
            <%= customer.last_name %><%= customer.first_name %>
            <% end %>
          </td>
          <td><%= customer.email %></td>
          <td>
    	      <% if customer.is_deleted? %>
    	      <span>退会</span>
    	      <% else %>
    	      <span>有効</span>
    	      <% end %>
    	    </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <div class="mx-auto">
      <%= paginate @customers %>
    </div>

  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-4 offset-sm-1 my-4">
			<h4 class="text-center bg-light"><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</h4>
		</div>
	</div>
	<div class="row">
	  <table class="table-borderless col-sm-8 offset-sm-1 mt-4">
	    <tr>
	      <th class="col-sm-2">会員ID</th>
	      <td class="col-sm-6"><%= @customer.id %></td>
	    </tr>
	    <tr>
	      <th class="col-sm-2">氏名</th>
	      <td class="col-sm-6"><%= @customer.last_name %>  <%= @customer.first_name %></td>
	    </tr>
	    <tr>
	      <th class="col-sm-2">フリガナ</th>
	      <td class="col-sm-6"><%= @customer.last_name_kana %>  <%= @customer.first_name_kana %></td>
	    </tr>
	    <tr>
	      <th class="col-sm-2">郵便番号</th>
	      <td class="col-sm-6"><%= @customer.postal_code %></td>
	    </tr>
	    <tr>
	      <th class="col-sm-2">住所</th>
	      <td class="col-sm-6"><%= @customer.address %></td>
	    </tr>
	    <tr>
	      <th class="col-sm-2">電話番号</th>
	      <td class="col-sm-6"><%= @customer.telephone_number %></td>
	    </tr>
	    <tr>
	      <th class="col-sm-2">メールアドレス</th>
	      <td class="col-sm-6"><%= @customer.email %></td>
	    </tr>
	    <tr>
	      <th class="col-sm-2">会員ステータス</th>
	      <td class="col-sm-6">
	        <% if @customer.is_deleted? %>
    	    <span class="font-weight-bold">退会</span>
    	    <% else %>
    	    <span class="font-weight-bold text-success">有効</span>
    	    <% end %>
	      </td>
	    </tr>
    </table>
    <div class="col-sm-2 offset-sm-3 mt-4">
      <%= link_to edit_admin_customer_path(@customer) do %>
      <button type="button" class="btn btn-success">編集する</button>
      <% end %>
    </div>
    <div class="col-sm-3 mt-4">
      <%= link_to admin_path(order_sort: 0, customer_id: @customer.id) do %>
      <button type="button" class="btn btn-primary">注文履歴一覧を見る</button>
      <% end %>
    </div>
	</div>
</div>