config/routes.rb
Rails.application.routes.draw do

  devise_for :customers, path: 'customer', controllers: {
    sessions: "customers/sessions",
    registrations: "customers/registrations",
    passwords: "customers/passwords"
  }
  devise_for :admins, path: 'admin', controllers: {
    sessions: "admins/sessions"
  }

  namespace :admin do
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    patch 'orders/:order_id/order_details/:id' => 'order_details#update', as: 'order_detail'
  end
  get 'admin' => 'admin/homes#top'

  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'

    get 'customers/mypage' => 'customers#show'
    get 'customers/edit' => 'customers#edit'
    patch 'customers' => 'customers#update'
    put 'customers' => 'customers#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw'

    resources :addresses, only: [:index, :edit, :create, :update, :destroy]

    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]


    resources :items, only: [:index, :show]

    get 'orders/thanks' => 'orders#thanks'
    resources :orders, only: [:new, :create, :index, :show]
    post 'orders/confirm' => 'orders#confirm'

  end


end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def pan
    "〒" + postal_code + " " + address + " " + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy

  def active_for_authentication?
    super && (self.is_deleted == false)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord

   belongs_to :genre
   has_many :cart_items
   has_many :order_details
   
   attachment :image

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum payment_method: {クレジットカード: 0, 銀行振込: 1}
  enum status: {入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済: 4}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :item

  enum making_status: {製作不可: 0, 製作待ち: 1, 製作中: 2, 製作完了: 3}
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    @customers = Customer.all.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path
  end

  private
  def customer_params
  		params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :address, :postal_code, :telephone_number, :email, :is_deleted)
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    if params[:order_sort] == "0"
      @customer = Customer.find(params[:customer_id])
      @orders = @customer.orders.page(params[:page]).per(10)
    else
    @orders = Order.all.page(params[:page]).per(10)
    end
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all.page(params[:page]).per(10)
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item)
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item)
  end

  private

  def item_params
    params.require(:item).permit(:genre_id, :name, :image, :introduction, :price, :is_active)
  end


end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order.delivery_charge = 800
    @order_details = @order.order_details
    @total_price = 0
    @order_details.each do |detail|
      @total_price += detail.purchase_price*detail.amount
    end
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    if @order.status == "入金確認"
      @order.order_details.each do |detail|
        detail.update(making_status: "製作待ち")
      end
    end
    redirect_to admin_order_path
  end

  private

  def order_params
    params.require(:order).permit(:status)
  end

end

app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?


 

  def after_sign_in_path_for(resource)
	case resource
	when Admin
	   admin_path
	when Customer
	   root_path
	end
  end

  def after_sign_out_path_for(resource)

 	case resource
 	when :admin
 		new_admin_session_path
 	when :customer
 		root_path
 	end
  end


	protected
		def configure_permitted_parameters
			devise_parameter_sanitizer.permit(:sign_up, keys:[:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
		end


end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def addTax(price)
    tax_included_price = (price * 1.1).round
  end

  def sumprice(price,postprice)
    return addTax(price) + postprice
  end
end

app/views/admin/genres/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-3 offset-sm-1 my-4">
			<h4 class="text-center bg-light">ジャンル編集</h4>
		</div>
	</div>
	<div class="row">
	  <%= form_with model: [:admin, @genre], local:true do |f| %>
    <div class="form-inline">
      <label for="inputgenre" class="my-4 mr-5 ml-4 col-form-label">ジャンル名</label>
      <%= f.text_field :name, class: "form-control my-4 mr-5", placeholder: "ジャンル名" %>
      <%= f.submit '変更を保存', class: "btn btn-success my-4" %>
    </div>
    <% end %>
	</div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-3 offset-sm-1 my-4">
			<h4 class="text-center bg-light">ジャンル一覧・追加</h4>
		</div>
	</div>
	<div class="row">
	  <%= form_with model: [:admin, @genre], local:true do |f| %>
    <div class="form-inline">
      <label for="inputgenre" class="my-4 mr-5 ml-4 col-form-label">ジャンル名</label>
      <%= f.text_field :name, class: "form-control my-4 mr-5", placeholder: "ジャンル名" %>
      <%= f.submit '新規登録', class: "btn btn-success my-4" %>
    </div>
    <% end %>
	</div>
	<div class="row">
	  <table class="table col-sm-4 ml-1 mt-4">
      <thead class="thead-light">
        <tr>
          <th class="text-center col-sm-2">ジャンル</th>
          <th class="col-sm-2"></th>
        </tr>
      </thead>
      <tbody>
        <% @genres.each do |genre| %>
        <tr>
          <td class="col-sm-2"><%= genre.name %></td>
          <td class="text-center col-sm-2">
            <%= link_to edit_admin_genre_path(genre.id) do %>
            <button type="button" class="btn btn-success btn-sm">編集する</button>
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
	</div>


</div>

app/views/admin/items/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-3 offset-sm-1 my-4">
			<h4 class="text-center bg-light">商品編集</h4>
		</div>
	</div>
	<div class="row">
	  <div class="col-sm-8 mx-auto">
	    <%= form_with model: [:admin, @item], local:true do |f| %>
	    <div class="form-group row">
	      <label for="inputimage" class="col-sm-3 offset-sm-1 col-form-label">商品画像</label>
	      <div class="col-sm-6">
	        <%= f.attachment_field :image, class: "form-control-file" %>
	      </div>
	    </div>
      <div class="form-group row">
        <label for="inputname" class="col-sm-3 offset-sm-1 col-form-label">商品名</label>
        <div class="col-sm-6">
          <%= f.text_field :name, class: "form-control" %>
        </div>
      </div>
      <div class="form-group row">
        <label for="inputintroduction" class="col-sm-3 offset-sm-1 col-form-label">商品説明</label>
        <div class="col-sm-6">
          <%= f.text_area :introduction, class: "form-control" %>
        </div>
      </div>
      <div class="form-group row">
        <label for="inputgenre" class="col-sm-3 offset-sm-1 col-form-label">ジャンル</label>
        <div class="col-sm-6">
          <%= f.collection_select :genre_id, Genre.all, :id, :name, {prompt: "--選択してください--"}, {class: "form-control"} %>
        </div>
      </div>
      <div class="form-group row">
        <label for="inputprice" class="col-sm-3 offset-sm-1 col-form-label">税抜価格</label>
        <div class="col-sm-6">
          <%= f.text_field :price, class: "form-control" %>
        </div>
      </div>
      <div class="form-group row">
        <label for="inputstatus" class="col-sm-3 offset-sm-1 col-form-label">販売ステータス</label>
        <div class="col-sm-6">
          <div class="form-check form-check-inline">
            <%= f.radio_button :is_active, :true, class: "form-check-input" %>
            <label class="form-check-label" for="inlineCheckboxTrue">販売中</label>
          </div>
          <div class="form-check form-check-inline">
            <%= f.radio_button :is_active, :false, class: "form-check-input" %>
            <label class="form-check-label" for="inlineCheckboxFalse">販売停止中</label>
          </div>
        </div>
      </div>
      <div class="form-group row">
          <div class="col-sm-6 offset-sm-4">
          <%= f.submit "変更を保存", class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
	  </div>
	</div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-3 offset-sm-1 my-4">
			<h4 class="text-center bg-light">商品一覧</h4>
		</div>
		<div class="col-sm-1 offset-sm-6 my-4">
			<%= link_to new_admin_item_path do %>
		  <i class="fas fa-plus fa-2x rounded-circle shadow-lg"></i>
		  <% end %>
		</div>
		<table class="table col-sm-10 offset-sm-1">
		  <thead class="thead-light">
				<tr>
					<th>商品ID</th>
					<th>商品名</th>
					<th>税抜価格</th>
					<th>ジャンル</th>
					<th>ステータス</th>
				</tr>
			</thead>
			<tbody>
			  <% @items.each do |item| %>
			  <tr>
			    <td><%= item.id %></td>
			    <td>
			    	<%= link_to admin_item_path(item) do %>
			    	<%= item.name %>
			    	<% end %>
			    </td>
			    <td><%= item.price %></td>
			    <td><%= item.genre.name %></td>
			    <td>
			      <% if item.is_active? %>
			      <span>販売中</span>
			      <% else %>
			      <span>販売停止</span>
			      <% end %>
			    </td>
			  </tr>
			  <% end %>
			</tbody>
    </table>
    <div class="mx-auto">
    	<%= paginate @items %>
    </div>
	</div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-3 offset-sm-1 my-4">
			<h4 class="text-center bg-light">商品新規登録</h4>
		</div>
	</div>
	<div class="row">
	  <div class="col-sm-8 mx-auto">
	    <%= form_with model: [:admin, @item], local:true do |f| %>
	    <div class="form-group row">
	      <label for="inputimage" class="col-sm-3 offset-sm-1 col-form-label">商品画像</label>
	      <div class="col-sm-6">
	        <%= f.attachment_field :image, class: "form-control-file" %>
	      </div>
	    </div>
      <div class="form-group row">
        <label for="inputname" class="col-sm-3 offset-sm-1 col-form-label">商品名</label>
        <div class="col-sm-6">
          <%= f.text_field :name, class: "form-control" %>
        </div>
      </div>
      <div class="form-group row">
        <label for="inputintroduction" class="col-sm-3 offset-sm-1 col-form-label">商品説明</label>
        <div class="col-sm-6">
          <%= f.text_area :introduction, class: "form-control" %>
        </div>
      </div>
      <div class="form-group row">
        <label for="inputgenre" class="col-sm-3 offset-sm-1 col-form-label">ジャンル</label>
        <div class="col-sm-6">
          <%= f.collection_select :genre_id, Genre.all, :id, :name, {prompt: "--選択してください--"}, {class: "form-control"} %>
        </div>
      </div>
      <div class="form-group row">
        <label for="inputprice" class="col-sm-3 offset-sm-1 col-form-label">税抜価格</label>
        <div class="col-sm-6">
          <%= f.text_field :price, class: "form-control" %>
        </div>
      </div>
      <div class="form-group row">
        <label for="inputstatus" class="col-sm-3 offset-sm-1 col-form-label">販売ステータス</label>
        <div class="col-sm-6">
          <div class="form-check form-check-inline">
            <%= f.radio_button :is_active, :true, class: "form-check-input" %>
            <label class="form-check-label" for="inlineCheckboxTrue">販売中</label>
          </div>
          <div class="form-check form-check-inline">
            <%= f.radio_button :is_active, :false, class: "form-check-input" %>
            <label class="form-check-label" for="inlineCheckboxFalse">販売停止中</label>
          </div>
        </div>
      </div>
      <div class="form-group row">
          <div class="col-sm-6 offset-sm-4">
          <%= f.submit "新規登録", class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
	  </div>
	</div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-3 offset-sm-1 my-4">
			<h4 class="text-center bg-light">商品詳細</h4>
		</div>
	</div>
	<div class="row">
	  <div class="col-sm-3 offset-sm-1 mt-4 mr-2">
	    <%= attachment_image_tag @item, :image, class: "img-fluid" %>
	  </div>
	  <table class="table-borderless col-sm-6 mt-4 ml-2">
	    <tr>
	      <th class="col-sm-1 small">商品名</th>
	      <td class="col-sm-3"><%= @item.name %></td>
	    </tr>
	    <tr>
	      <th class="col-sm-1 small">説明</th>
	      <td class="col-sm-3"><%= @item.introduction %></td>
	    </tr>
	    <tr>
	      <th class="col-sm-1 small">ジャンル</th>
	      <td class="col-sm-3"><%= @item.genre.name %></td>
	    </tr>
	    <tr>
	      <th class="col-sm-1 small">税込価格<br/>
	      (税抜価格)</th>
	      <td class="col-sm-3"><strong><%= addTax(@item.price) %> (<%= @item.price %>)</strong> 円</td>
	    </tr>
	    <tr>
	      <th class="col-sm-1 small">販売ステータス</th>
	      <td class="col-sm-3">
	        <% if @item.is_active? %>
    	    <span class="font-weight-bold text-success">販売中</span>
    	    <% else %>
    	    <span class="font-weight-bold">販売停止</span>
    	    <% end %>
	      </td>
	    </tr>
    </table>
    <div class="col-sm-2 offset-sm-5 mt-4">
      <%= link_to edit_admin_item_path(@item) do %>
      <button type="button" class="btn btn-success btn-lg">編集する</button>
      <% end %>
    </div>

	 </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-3 offset-sm-1 my-4">
			<h4 class="text-center bg-light">注文履歴詳細</h4>
		</div>
	</div>
	<div class="row">
	  <div class="col-sm-12 my-2">
	    <table class="table table-borderless col-sm-10">
	      <tr>
	        <th class="col-sm-2">購入者</th>
	        <td class="col-sm-6"><%= @order.customer.last_name %><%= @order.customer.first_name %></td>
	      </tr>
	      <tr>
	        <th class="col-sm-2">注文日</th>
	        <td class="col-sm-6"><%= @order.created_at.strftime('%Y/%m/%d') %></td>
	      </tr>
	      <tr>
	        <th class="col-sm-2">配送先</th>
	        <td class="col-sm-6"><%= @order.address %></td>
	      </tr>
	      <tr>
	        <th class="col-sm-2">支払方法</th>
	        <td class="col-sm-6"><%= @order.payment_method %></td>
	      </tr>
	      <tr>
	        <th class="col-sm-2">注文ステータス</th>
	        <td class="col-sm-6">
	          <%= form_with model: @order, url: admin_order_path, local:true do |f| %>
	          <div class="form-group row">
	            <%= f.select :status, {入金待ち: "入金待ち", 入金確認: "入金確認", 製作中: "製作中", 発送準備中: "発送準備中", 発送済: "発送済"}, {}, class: "form-control w-25 ml-2"%>
              <%= f.submit "更新", class: "btn btn-success offset-sm-1" %>
            </div>
            <% end %>
	        </td>
	      </tr>
	    </table>
	  </div>
	</div>
	<div class="row">
	  <div class="col-sm-8">
	    <table class="table table-bordered">
	      <thead class="thead-light">
	        <tr>
            <th>商品</th>
            <th>単価（税込）</th>
            <th>個数</th>
            <th>小計</th>
            <th>製作ステータス</th>
          </tr>
	      </thead>
	      <tbody>
          <% @order_details.each do |detail| %>
          <tr>
            <td><%= detail.item.name %></td>
            <td><%= addTax(detail.purchase_price) %></td>
            <td><%= detail.amount %></td>
            <td><%= addTax(detail.purchase_price)*detail.amount %></td>
            <td>
              <%= form_with model: detail, url: admin_order_detail_path(@order,detail), local:true do |f| %>
              <div class="form-group row">
                <%= f.select :making_status, {製作不可: "製作不可", 製作待ち: "製作待ち", 製作中: "製作中", 製作完了: "製作完了"}, {}, class: "form-control w-50 ml-3 mr-1" %>
                <%= f.submit "更新", class: "btn btn-success" %>
              </div>

              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
	    </table>

	  </div>
	  <div class="col-sm-3 offset-sm-1">
	    <table class="table table-borderless">
	      <tr>
	        <th>送料</th>
	        <td><%= @order.delivery_charge %></td>
	      </tr>
	      <tr>
	        <th>商品合計</th>
	        <td><%= addTax(@total_price) %></td>
	      </tr>
	      <tr>
	        <th>請求金額</th>
	        <td><%= @order.total_payment %></td>
	      </tr>
	    </table>
	  </div>
	</div>
</div>