config/routes.rb
Rails.application.routes.draw do

  devise_for :customers, path: 'customer', controllers: {
    sessions: "customers/sessions",
    registrations: "customers/registrations",
    passwords: "customers/passwords"
  }
  devise_for :admins, path: 'admin', controllers: {
    sessions: "admins/sessions"
  }

  namespace :admin do
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    patch 'orders/:order_id/order_details/:id' => 'order_details#update', as: 'order_detail'
  end
  get 'admin' => 'admin/homes#top'

  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'

    get 'customers/mypage' => 'customers#show'
    get 'customers/edit' => 'customers#edit'
    patch 'customers' => 'customers#update'
    put 'customers' => 'customers#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw'

    resources :addresses, only: [:index, :edit, :create, :update, :destroy]

    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]


    resources :items, only: [:index, :show]

    get 'orders/thanks' => 'orders#thanks'
    resources :orders, only: [:new, :create, :index, :show]
    post 'orders/confirm' => 'orders#confirm'

  end


end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def pan
    "〒" + postal_code + " " + address + " " + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy

  def active_for_authentication?
    super && (self.is_deleted == false)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord

   belongs_to :genre
   has_many :cart_items
   has_many :order_details
   
   attachment :image

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum payment_method: {クレジットカード: 0, 銀行振込: 1}
  enum status: {入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済: 4}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :item

  enum making_status: {製作不可: 0, 製作待ち: 1, 製作中: 2, 製作完了: 3}
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    if params[:order_sort] == "0"
      @customer = Customer.find(params[:customer_id])
      @orders = @customer.orders.page(params[:page]).per(10)
    else
    @orders = Order.all.page(params[:page]).per(10)
    end
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all.page(params[:page]).per(10)
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item)
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item)
  end

  private

  def item_params
    params.require(:item).permit(:genre_id, :name, :image, :introduction, :price, :is_active)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?


 

  def after_sign_in_path_for(resource)
	case resource
	when Admin
	   admin_path
	when Customer
	   root_path
	end
  end

  def after_sign_out_path_for(resource)

 	case resource
 	when :admin
 		new_admin_session_path
 	when :customer
 		root_path
 	end
  end


	protected
		def configure_permitted_parameters
			devise_parameter_sanitizer.permit(:sign_up, keys:[:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
		end


end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def addTax(price)
    tax_included_price = (price * 1.1).round
  end

  def sumprice(price,postprice)
    return addTax(price) + postprice
  end
end

app/views/layouts/_adminheader.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-white bo">
  <div class="container">
   <a class="navbar-brand" href="/admin/sign_in">
    <span>logo</span>
   </a>
   <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
   </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
     <ul class="navbar-nav ml-auto">
       <li>
        <%= link_to admin_items_path do %>
        <button type="button" class="btn btn-outline-secondary m-2">商品一覧</button>
        <% end %>
       </li>
       <li>
        <%= link_to admin_customers_path do %>
        <button type="button" class="btn btn-outline-secondary m-2">会員一覧</button>
        <% end %>
       </li>
       <li>
        <%= link_to admin_path do %>
        <button type="button" class="btn btn-outline-secondary m-2">注文履歴一覧</button>
        <% end %>
       </li>
       <li>
        <%= link_to admin_genres_path do %>
        <button type="button" class="btn btn-outline-secondary m-2">ジャンル一覧</button>
        <% end %>
       </li>
       <li>
        <%= link_to destroy_admin_session_path, method: :delete do %>
        <button type="button" class="btn btn-outline-secondary m-2">ログアウト</button>
        <% end %>
       </li>
     </ul>
    </div>
  </div>
</nav>

app/views/layouts/_publicheader.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-w">
  <div class="container">
   <a class="navbar-brand" href="/">
    <span>logo</span>
   </a>
   <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
   </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
     <ul class="navbar-nav ml-auto">
      <% if customer_signed_in? %>
      <li class="d-flex align-items-center">
        ようこそ、<%= current_customer.last_name %> さん！
      </li>
      <li>
        <%= link_to customers_mypage_path do %>
        <button type="button" class="btn btn-outline-secondary m-2">マイページ</button>
       <% end %>
      </li>
      <li>
        <%= link_to items_path do %>
        <button type="button" class="btn btn-outline-secondary m-2">商品一覧</button>
        <% end %>
      </li>
      <li>
        <%= link_to cart_items_path do %>
        <button type="button" class="btn btn-outline-secondary m-2">カート</button>
        <% end %>
      </li>
      <li>
        <%= link_to destroy_customer_session_path, method: :delete do %>
        <button type="button" class="btn btn-outline-secondary m-2">ログアウト</button>
        <% end %>
      </li>
      <% else %>
      <li>
        <%= link_to about_path do %>
        <button type="button" class="btn btn-outline-secondary m-2">About</button>
        <% end %>
      </li>
      <li>
        <%= link_to items_path do %>
        <button type="button" class="btn btn-outline-secondary m-2">商品一覧</button>
        <% end %>
      </li>
      <li>
        <%= link_to new_customer_registration_path do %>
        <button type="button" class="btn btn-outline-secondary m-2">新規登録</button>
        <% end %>
      </li>
      <li>
        <%= link_to new_customer_session_path do %>
        <button type="button" class="btn btn-outline-secondary m-2">ログイン</button>
        <% end %>
      </li>
      <% end %>
     </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="border">
    <% if admin_signed_in? %>
     <%= render 'layouts/adminheader' %>
    <% else %>
     <%= render 'layouts/publicheader' %>
    <% end %>
    </header>
    <main>
     <%= yield %>
    </main>
    <footer>

    </footer>

  </body>
</html>